spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: client-01-route
              uri: lb://CLIENT-01
              predicates:
                - Path=/client-01/**
              filters:
                - StripPrefix=1
#
#            - id: identity-service-route
#              uri: lb://IDENTITY-SERVICE
#              predicates:
#                - Path=/identity-service/**
#              filters:
#                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #    register-with-eureka: false
    registry-fetch-interval-seconds: 5
  instance:
    hostname: localhost

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health , info, prometheus
